# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      run: pytest tests/ -v --cov=src --cov-report=term-missing
    
    - name: Lint code
      run: pylint --disable=R,C src/ tests/ || true

  docker:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t scvsai:latest .
    
    - name: Test Docker workflows
      run: |
        # Test EDA
        docker run --rm -v $PWD/data:/app/data scvsai:latest make eda
        
        # Test quick training  
        docker run --rm -v $PWD/models:/app/models scvsai:latest python -c "from src.train import train_model; train_model(epochs=1)"
        
        # Test suite
        docker run --rm scvsai:latest make test
    
    - name: Success notification
      run: |
        echo "✅ All tests passed!"
        echo "✅ Docker image built successfully!"
        echo "✅ CI/CD pipeline completed!"